<?php
/**
 * Protects the IMMUTABLE migration-parity baselines. These PNGs photograph a
 * frontend that no longer exists once the classic theme is deleted, so nothing
 * in the repository may be able to silently regenerate them — in particular,
 * `playwright test --update-snapshots` must have no path to them.
 *
 * @package Tests\Architecture
 */

declare(strict_types=1);

namespace Tests\Architecture;

use PHPUnit\Framework\TestCase;
use Tests\Support\FormatsArchitectureFailures;

require_once dirname( __DIR__ ) . '/support/FormatsArchitectureFailures.php';

final class MigrationBaselineGuardTest extends TestCase {

	use FormatsArchitectureFailures;

	private const BASELINE_RELATIVE      = 'tests/parity/__migration_baselines__';
	private const DEFAULT_MAX_DIFF_RATIO = 0.05;

	/**
	 * @return array<string, mixed>
	 */
	private function metadata(): array {
		$path = $this->repo_root() . '/' . self::BASELINE_RELATIVE . '/metadata.json';

		self::assertFileExists( $path, 'Migration baselines must carry a metadata.json sidecar.' );

		$decoded = json_decode( $this->read( $path ), true );

		self::assertIsArray( $decoded, 'metadata.json must be a JSON object.' );

		return $decoded;
	}

	public function test_metadata_records_every_reproducibility_field(): void {
		$metadata = $this->metadata();

		$required = array(
			'capturedAtCommit',
			'capturedAtUtc',
			'runnerImage',
			'browser',
			'browserVersion',
			'playwrightVersion',
			'fontStack',
			'contentFixtures',
			'projects',
			'pages',
		);

		foreach ( $required as $key ) {
			self::assertArrayHasKey(
				$key,
				$metadata,
				$this->architecture_failure(
					'Migration baseline metadata is missing a reproducibility field',
					self::BASELINE_RELATIVE . '/metadata.json',
					'A baseline that does not record the browser, viewport, fixtures, fonts and commit it was taken at cannot be trusted or reproduced.',
					'Add the "' . $key . '" key with the value the capture run actually used.'
				)
			);

			self::assertNotSame(
				'TO-BE-FILLED-BY-CAPTURE-RUN',
				$metadata[ $key ] ?? null,
				'metadata.json still holds a capture-run placeholder for "' . $key . '".'
			);
		}
	}

	public function test_every_declared_baseline_png_exists(): void {
		$metadata = $this->metadata();
		$root     = $this->repo_root() . '/' . self::BASELINE_RELATIVE;

		foreach ( array_keys( (array) $metadata['projects'] ) as $project ) {
			foreach ( (array) $metadata['pages'] as $page ) {
				$name = (string) ( $page['name'] ?? '' );

				self::assertFileExists(
					$root . '/' . $project . '/' . $name . '.png',
					$this->architecture_failure(
						'Declared migration baseline is missing on disk',
						self::BASELINE_RELATIVE . '/' . $project . '/' . $name . '.png',
						'metadata.json declares this baseline, so the parity suite will try to compare against it.',
						'Re-run the capture workflow against the pre-migration commit and commit the uploaded artifact.'
					)
				);
			}
		}
	}

	public function test_no_page_can_raise_the_five_percent_limit(): void {
		$helper = $this->read( $this->repo_root() . '/tests/parity/helpers/parity.ts' );

		// Every ParityPage literal is one { ... } block. The master specification
		// sets five percent as the maximum, not a default that pages may raise.
		preg_match_all( '/\{[^{}]*maxDiffRatio\s*:[^{}]*\}/', $helper, $entries );

		foreach ( $entries[0] as $entry ) {
			if ( 1 !== preg_match( '/maxDiffRatio\s*:\s*([0-9.]+)/', $entry, $ratio ) ) {
				continue;
			}

			self::assertLessThanOrEqual(
				self::DEFAULT_MAX_DIFF_RATIO,
				(float) $ratio[1],
				$this->architecture_failure(
					'A parity page raises its threshold above ' . self::DEFAULT_MAX_DIFF_RATIO,
					'tests/parity/helpers/parity.ts',
					'The release gate permits no page above five percent.',
					'Correct the rendering or mask only a proven nondeterministic region: ' . $entry
				)
			);
		}

		$this->addToAssertionCount( 1 );
	}

	public function test_no_spec_can_regenerate_a_migration_baseline(): void {
		foreach ( $this->spec_files() as $file ) {
			$contents  = $this->read( $file );
			$is_parity = str_contains( str_replace( '\\', '/', $file ), '/tests/parity/' );

			if ( ! $is_parity && ! str_contains( $contents, '__migration_baselines__' ) ) {
				continue;
			}

			self::assertStringNotContainsString(
				'toHaveScreenshot',
				$contents,
				$this->architecture_failure(
					'A parity/baseline spec uses toHaveScreenshot()',
					$this->to_relative( $file ),
					'toHaveScreenshot() baselines are regenerated by `--update-snapshots`, which would let an agent overwrite the pre-migration evidence and make a regression pass.',
					'Compare with pixelmatch through compareToBaseline() in tests/parity/helpers/parity.ts instead.'
				)
			);
		}

		$this->addToAssertionCount( 1 );
	}

	public function test_baselines_live_outside_the_playwright_snapshot_tree(): void {
		$config = $this->read( $this->repo_root() . '/playwright.config.ts' );

		self::assertStringContainsString(
			'__screenshots__',
			$config,
			'playwright.config.ts must keep resolving snapshots under __screenshots__, away from __migration_baselines__.'
		);

		self::assertStringNotContainsString(
			'__migration_baselines__',
			$config,
			'playwright.config.ts must not teach Playwright how to resolve migration baselines as snapshots.'
		);

		self::assertDirectoryDoesNotExist(
			$this->repo_root() . '/tests/visual/__screenshots__/__migration_baselines__',
			'Migration baselines must never live under the Playwright snapshot directory.'
		);
	}

	/**
	 * @return list<string>
	 */
	private function spec_files(): array {
		$root = $this->repo_root() . '/tests';
		$out  = array();

		$iterator = new \RecursiveIteratorIterator(
			new \RecursiveDirectoryIterator( $root, \FilesystemIterator::SKIP_DOTS )
		);

		foreach ( $iterator as $item ) {
			if ( $item instanceof \SplFileInfo && $item->isFile() && str_ends_with( $item->getFilename(), '.ts' ) ) {
				$out[] = $item->getPathname();
			}
		}

		sort( $out );

		return $out;
	}

	private function read( string $file ): string {
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- static source inspection in the architecture suite; no WordPress runtime here.
		$source = file_get_contents( $file );

		return false === $source ? '' : $source;
	}
}
