<?php
/**
 * Generates the deterministic Markdown block index shared by
 * scripts/generate-block-index (which writes it to disk) and
 * GeneratedIndexFreshnessTest (which asserts the committed copy is current).
 *
 * The output is intentionally timestamp-free: any non-deterministic content
 * would make the freshness check impossible. Paths are forward-slashed and
 * every list is sorted so the result is byte-identical on every platform.
 *
 * Required explicitly (not PSR-4 autoloaded) for the case-sensitivity reason
 * documented in ArchitectureScanner.php.
 *
 * @package Tests\Support
 */

declare(strict_types=1);

namespace Tests\Support;

/**
 * @internal
 */
final class BlockIndexGenerator {

	private const THEME_RELATIVE = 'web/app/themes/site-theme';

	private const FILE_ASSET_KEYS = array(
		'render'       => 'Render',
		'editorScript' => 'Editor script',
		'style'        => 'Style',
		'editorStyle'  => 'Editor style',
	);

	private function __construct() {
		// Static-only API; never instantiated.
	}

	/**
	 * Builds the full Markdown document for the theme's blocks.
	 */
	public static function generate( string $repo_root ): string {
		$root  = rtrim( str_replace( '\\', '/', $repo_root ), '/' );
		$theme = $root . '/' . self::THEME_RELATIVE;

		$rows = array();

		foreach ( self::block_directories( $theme . '/blocks' ) as $block_dir ) {
			$manifest = self::decode( $block_dir . '/block.json' );

			if ( null === $manifest ) {
				continue;
			}

			$rows[] = self::row( $root, $theme, $block_dir, $manifest );
		}

		return self::document( $rows );
	}

	/**
	 * @param array<mixed> $manifest
	 * @return array<string, string>
	 */
	private static function row( string $root, string $theme, string $block_dir, array $manifest ): array {
		$name = is_string( $manifest['name'] ?? null ) ? $manifest['name'] : basename( $block_dir );
		$slug = basename( $block_dir );

		$assets = array();

		foreach ( self::FILE_ASSET_KEYS as $key => $_label ) {
			$assets[ $key ] = self::asset_cell( $manifest[ $key ] ?? null );
		}

		return array(
			'name'         => '`' . $name . '`',
			'title'        => is_string( $manifest['title'] ?? null ) ? $manifest['title'] : '—',
			'folder'       => '`' . self::relative( $root, $block_dir ) . '`',
			'render'       => $assets['render'],
			'editorScript' => $assets['editorScript'],
			'style'        => $assets['style'],
			'editorStyle'  => $assets['editorStyle'],
			'patterns'     => self::references_cell( $root, self::files_containing( $theme . '/patterns', $name, false ) ),
			'templates'    => self::references_cell( $root, self::files_containing( $theme . '/templates', $name, false ) ),
			'tests'        => self::references_cell( $root, self::related_tests( $root, $slug ) ),
		);
	}

	/**
	 * @param list<array<string, string>> $rows
	 */
	private static function document( array $rows ): string {
		$lines = array(
			'# Generated Block Index',
			'',
			'<!--',
			'  DO NOT EDIT BY HAND.',
			'  Generated by scripts/generate-block-index from each block\'s block.json and the',
			'  patterns, templates, and tests that reference it. Regenerate with',
			'  `php scripts/generate-block-index` and commit the result; the architecture suite\'s',
			'  GeneratedIndexFreshnessTest fails if this file drifts from the code.',
			'-->',
			'',
			'| Block | Title | Folder | Render | Editor script | Style | Editor style | Patterns | Templates | Tests |',
			'| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |',
		);

		foreach ( $rows as $row ) {
			$lines[] = '| ' . implode(
				' | ',
				array(
					$row['name'],
					$row['title'],
					$row['folder'],
					$row['render'],
					$row['editorScript'],
					$row['style'],
					$row['editorStyle'],
					$row['patterns'],
					$row['templates'],
					$row['tests'],
				)
			) . ' |';
		}

		$lines[] = '';

		return implode( "\n", $lines );
	}

	private static function asset_cell( mixed $value ): string {
		if ( ! is_string( $value ) || ! str_starts_with( $value, 'file:' ) ) {
			return '—';
		}

		$path = ltrim( substr( $value, strlen( 'file:' ) ), './' );

		return '' === $path ? '—' : '`' . $path . '`';
	}

	/**
	 * @param list<string> $absolute_paths
	 */
	private static function references_cell( string $root, array $absolute_paths ): string {
		if ( array() === $absolute_paths ) {
			return '—';
		}

		return implode(
			'<br>',
			array_map(
				static fn( string $path ): string => '`' . self::relative( $root, $path ) . '`',
				$absolute_paths
			)
		);
	}

	/**
	 * PHP files directly inside $dir whose contents contain $needle.
	 *
	 * @return list<string> Absolute, sorted paths.
	 */
	private static function files_containing( string $dir, string $needle, bool $recursive ): array {
		$found = array();

		foreach ( self::list_files( $dir, $recursive ) as $file ) {
			if ( 'php' !== strtolower( pathinfo( $file, PATHINFO_EXTENSION ) ) ) {
				continue;
			}

			if ( str_contains( self::read( $file ), $needle ) ) {
				$found[] = $file;
			}
		}

		sort( $found );

		return $found;
	}

	/**
	 * Tests related to a block: any file under tests/ whose name or contents
	 * mention the block slug, EXCLUDING tests/Architecture/ — the enforcement
	 * layer names block slugs to police structure, not to exercise a block,
	 * so including it would make this index churn on every rule-message edit.
	 *
	 * @return list<string> Repo-relative-input absolute paths, sorted.
	 */
	private static function related_tests( string $root, string $slug ): array {
		$tests_dir = $root . '/tests';
		$found     = array();

		foreach ( self::list_files( $tests_dir, true ) as $file ) {
			$normalized = str_replace( '\\', '/', $file );

			if ( str_contains( $normalized, '/tests/Architecture/' ) ) {
				continue;
			}

			if ( str_contains( basename( $file ), $slug ) || str_contains( self::read( $file ), $slug ) ) {
				$found[] = $file;
			}
		}

		sort( $found );

		return $found;
	}

	/**
	 * @return list<string> Absolute block directory paths, sorted.
	 */
	private static function block_directories( string $blocks_dir ): array {
		if ( ! is_dir( $blocks_dir ) ) {
			return array();
		}

		$entries = scandir( $blocks_dir );

		if ( false === $entries ) {
			return array();
		}

		$dirs = array();

		foreach ( $entries as $entry ) {
			$path = $blocks_dir . '/' . $entry;

			if ( '.' !== $entry && '..' !== $entry && is_dir( $path ) ) {
				$dirs[] = $path;
			}
		}

		sort( $dirs );

		return $dirs;
	}

	/**
	 * @return list<string> Absolute file paths (build/vendor/node_modules skipped).
	 */
	private static function list_files( string $dir, bool $recursive ): array {
		if ( ! is_dir( $dir ) ) {
			return array();
		}

		if ( ! $recursive ) {
			$entries = scandir( $dir );

			if ( false === $entries ) {
				return array();
			}

			$files = array();

			foreach ( $entries as $entry ) {
				$path = $dir . '/' . $entry;

				if ( is_file( $path ) ) {
					$files[] = $path;
				}
			}

			return $files;
		}

		$skip     = array( 'vendor', 'node_modules', 'build' );
		$iterator = new \RecursiveIteratorIterator(
			new \RecursiveCallbackFilterIterator(
				new \RecursiveDirectoryIterator( $dir, \FilesystemIterator::SKIP_DOTS ),
				static fn( \SplFileInfo $current ): bool =>
					! ( $current->isDir() && in_array( $current->getFilename(), $skip, true ) )
			)
		);

		$files = array();

		foreach ( $iterator as $item ) {
			if ( $item instanceof \SplFileInfo && $item->isFile() ) {
				$files[] = $item->getPathname();
			}
		}

		return $files;
	}

	/**
	 * @return array<mixed>|null
	 */
	private static function decode( string $manifest ): ?array {
		if ( ! is_file( $manifest ) ) {
			return null;
		}

		$decoded = json_decode( self::read( $manifest ), true );

		return is_array( $decoded ) ? $decoded : null;
	}

	private static function relative( string $root, string $absolute ): string {
		$absolute = str_replace( '\\', '/', $absolute );
		$prefix   = $root . '/';

		return str_starts_with( $absolute, $prefix ) ? substr( $absolute, strlen( $prefix ) ) : $absolute;
	}

	private static function read( string $file ): string {
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- reading local project files to build a static index; runs outside WordPress.
		$contents = file_get_contents( $file );

		return false === $contents ? '' : $contents;
	}
}
